### ISSUE TITLE
 User None is not authorized to list kubeflow.org.v1beta1.notebooks for namespace: xxx

### ISSUE THREAD

**Issue by minglex** [minglex/issues#1]

**Comment by minglex** [comment]
从kubeflow进入notebookserver,点击创建notebook时出现该提示，用kubectl logs查看jupyter-web-app-deployment服务时提示：
2020-07-08 04:53:22,365 | kubeflow_jupyter.common.auth | WARNING | No user credentials were found! Make sure you have correctly set the USERID_HEADER in the Jupyter Web App's deployment.

**Comment by minglex** [comment]
原因是oidc-authservice模块中的envoy-filter.yaml内容被改变了，完整内容应该如下所示：
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authn-filter
spec:
  workloadLabels:
    istio: ingressgateway
  filters:
  - filterConfig:
      httpService:
        serverUri:
          uri: http://authservice.$(namespace).svc.cluster.local
          cluster: outbound|8080||authservice.$(namespace).svc.cluster.local
          failureModeAllow: false
          timeout: 10s
        authorizationRequest:
          allowedHeaders:
            patterns:
            - exact: "cookie"
            - exact: "X-Auth-Token"
        authorizationResponse:
          allowedUpstreamHeaders:
            patterns:
            - exact: "kubeflow-userid"
      statusOnError:
        code: GatewayTimeout
    filterName: envoy.ext_authz
    filterType: HTTP
    insertPosition:
      index: FIRST
    listenerMatch:
      listenerType: GATEWAY

```

当一下内容被注释时导致了该问题出现
```
        authorizationResponse:
          allowedUpstreamHeaders:
            patterns:
            - exact: "kubeflow-userid"
      statusOnError:
        code: GatewayTimeout
```
